#theme: jekyll-theme-minimal
title: CV
description: Aminda Suomalainen, verkkopalveluylläpitäjä/web service administrator
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://cv.aminda.eu" # the base hostname & protocol for your site
timezone: Europe/Helsinki
encoding: utf-8
plugins:
  - jekyll-sitemap
sitemap:
  file: "/sitemap.xml"
include: [robots.txt]
biosuomi: "Aminda Suomalainen on avointa lähdekoodia tukeva verkkopalveluylläpitäjä piraattipuolueessa"
bioenglish: "Short introduction text is coming here soon..."
icon: https://media.githubusercontent.com/media/Mikaela/mikaela.github.io/lfs-media/avatar/90.jpeg
