theme: minima
title: Curriculum Vitae
author: Aminda Suomalainen
description: >
  Sysadmin
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://cv.aminda.eu" # the base hostname & protocol for your site
timezone: Europe/Helsinki
encoding: utf-8
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sitemap:
  file: "/sitemap.xml"
include: [robots.txt]
icon: https://media.githubusercontent.com/media/Mikaela/mikaela.github.io/lfs-media/avatar/90.jpeg
linkedin_username: aminda-eu
github_username: Mikaela
email: suomalainen@mikaela.info
# Explicitly specify built with kramdown and options for it
markdown: kramdown
kramdown:
  # Required for entering html blocks within the markdown such as the unstyled
  # list
  parse_block_html: true
